---
- hosts: all
  tasks:
  
   - name: Add user "sysadmin" to remote server
     user:
       name: sysadmin
       comment: "Privileged User"
       uid: 2001
       append: yes
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa
...
