---
- name: httpd
  hosts: all
  tasks:
  - name: Install apache packages 
    yum:
      name: httpd
      state: removed
 
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
...      
